# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  yamlBasedBuilder:
    import: "package:i18n/builder.dart"
    builder_factories: ["yamlBasedBuilder"]
    build_extensions: {".i18n.yaml": [".i18n.dart"]}
    build_to: source
    auto_apply: root_package